version: "3.1"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - ${EXPOSE_PORT}:3000
    env_file:
      - .env
networks: 
  default:
    external: 
      name: pgsql
